package ue03_Messwerte;

import java.net.ServerSocket;
import java.net.Socket;
import java.util.concurrent.CancellationException;
import javax.swing.SwingWorker;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.io.*;

/**
 *
 * @author florian
 */
public class Server_GUI extends javax.swing.JFrame implements ChangeListener
{
  private ServerWorker sw;
  private double value;
  
  
  public Server_GUI ()
  {
    initComponents();  
    jSlider1.addChangeListener(this);
    jTextField1.setText(String.format("%.1f", value));
  }


  @Override
  public void stateChanged (ChangeEvent e)
  {
    if(e.getSource().equals(jSlider1))
    {
      value=(double) jSlider1.getValue()/10;
      jTextField1.setText(String.format("%.1f", value));
    }
  }

  
  private class ServerWorker extends SwingWorker<Object, Object>
  {
    private final int port;
    private final String requestPattern;
    private final String response;

    
    public ServerWorker (int port, String requestString, String responsePattern)
    {
      this.port = port;
      this.requestPattern = requestString;
      this.response = responsePattern; 
     }
    
    
    @Override
    protected Object doInBackground () throws Exception
    {
      ServerSocket ss = new ServerSocket(port);
      Socket socket = null;
      
      try
      {
        while(!isCancelled())
        { 
          socket=ss.accept();
          
          try(BufferedReader br=new BufferedReader(new InputStreamReader(socket.getInputStream())))
          {
            Thread.sleep(50);
            String request=br.readLine();
          
            if(request.equals(requestPattern))
            {
              try(BufferedWriter bw=new BufferedWriter(new OutputStreamWriter(socket.getOutputStream())))
              {
                bw.write(String.format(this.response, value));
              }
            }
            else
              System.out.println("Connection closed; wrong Request");
            
            socket.close();
          }
        }
      }
      finally
      {
        System.out.println("Close");
        ss.close();
        if(!(socket==null))
          socket.close();
      }
      return null;
    }


    @Override
    protected void done ()
    {
      try
      {
        get();
      }
      catch(CancellationException ex)
      {
        System.out.println("Thread Cancelled");
      }
      catch(Exception ex)
      {
        ex.printStackTrace(System.err);
      }
      finally
      {
        System.out.println("Server Closed");
        sw=null;
        jButton1.setText("Start Server");
      }
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jSlider1 = new javax.swing.JSlider();
    jTextField1 = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().add(jSlider1, java.awt.BorderLayout.CENTER);

    jTextField1.setText("1.1");
    jTextField1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jTextField1ActionPerformed(evt);
      }
    });
    getContentPane().add(jTextField1, java.awt.BorderLayout.PAGE_START);

    jPanel1.setLayout(new java.awt.GridLayout());

    jButton1.setText("Start Server");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton1);

    jButton2.setText("Beenden");
    jButton2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton2);

    getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
  {//GEN-HEADEREND:event_jTextField1ActionPerformed
    
  }//GEN-LAST:event_jTextField1ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
  {//GEN-HEADEREND:event_jButton1ActionPerformed
    if(sw==null)
    {
      jButton1.setText("Close Server");
      sw=new ServerWorker(4711, "GET", "%.1fV\n");
      sw.execute();
    }
    else
      sw.cancel(true);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
  {//GEN-HEADEREND:event_jButton2ActionPerformed
    if(sw!=null)
      sw.cancel(true);
    dispose();
  }//GEN-LAST:event_jButton2ActionPerformed


  /**
   * @param args the command line arguments
   */
  public static void main (String args[])
  {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(() ->
    {
      new Server_GUI().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSlider jSlider1;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables

}
